/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.breakabletoy;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("appHasAGreeting.....");
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
