/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.breakabletoy;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeTest {
    @Test public void appHasAGreeting() {
        Employee classUnderTest = new Employee();
        System.out.println("Employee appHasAGreeting.....");
        assertNotNull("Hello Employee!", classUnderTest.getGreeting());
    }
}
