/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.breakabletoy;

public class Employee {
    public String getGreeting() {
        return "Hello Employee!";
    }

    public static void main(String[] args) {
        System.out.println(new Employee().getGreeting());
    }
}
